version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:17"
      timezone: "America/New_York"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:27"
      timezone: "America/New_York"

  - package-ecosystem: "npm"
    directory: "/apps/lantern-garage"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:37"
      timezone: "America/New_York"
