[CmdletBinding()]
param(
    [switch]$Install,
    [switch]$Uninstall,
    [switch]$Status
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$RepoRoot = (git rev-parse --show-toplevel)
$HooksDir = Join-Path (Join-Path $RepoRoot ".git") "hooks"
$ScriptHooksDir = Join-Path (Join-Path $RepoRoot "scripts") "git-hooks"

if (-not (Test-Path -LiteralPath $HooksDir -PathType Container)) {
    throw "Git hooks directory not found: $HooksDir"
}

if (-not (Test-Path -LiteralPath $ScriptHooksDir -PathType Container)) {
    throw "Git hook scripts directory not found: $ScriptHooksDir"
}

$HookPlan = @(
    [pscustomobject]@{
        Name = "pre-commit"
        Preferred = "pre-commit-agent-identity.ps1"
        Fallback = "pre-commit-evidence-consistency"
        Purpose = "agent identity and evidence consistency"
    },
    [pscustomobject]@{
        Name = "pre-push"
        Preferred = "pre-push-pr-enforcement.ps1"
        Fallback = "pre-push-git-state-validation"
        Purpose = "PR and git-state safety checks"
    }
)

function Resolve-HookScript {
    param([pscustomobject]$Hook)

    $preferredPath = Join-Path $ScriptHooksDir $Hook.Preferred
    if (Test-Path -LiteralPath $preferredPath -PathType Leaf) {
        return $preferredPath
    }

    $fallbackPath = Join-Path $ScriptHooksDir $Hook.Fallback
    if (Test-Path -LiteralPath $fallbackPath -PathType Leaf) {
        return $fallbackPath
    }

    return $null
}

function New-HookWrapper {
    param(
        [string]$HookName,
        [string]$ScriptPath
    )

    $hookPath = Join-Path $HooksDir $HookName
    $scriptName = [System.IO.Path]::GetFileName($ScriptPath)
    $isPowerShellScript = $ScriptPath.EndsWith(".ps1", [System.StringComparison]::OrdinalIgnoreCase)

    $wrapper = if ($isPowerShellScript) {
@"
#!/bin/bash
# Generated by scripts/Install-GitHookEnforcement.ps1
REPO_ROOT=`$(git rev-parse --show-toplevel)
SCRIPT_PATH="`$REPO_ROOT/scripts/git-hooks/$scriptName"

if command -v pwsh >/dev/null 2>&1; then
  pwsh -NoProfile -ExecutionPolicy Bypass -File "`$SCRIPT_PATH" "`$@"
  exit `$?
fi
if command -v powershell >/dev/null 2>&1; then
  powershell -NoProfile -ExecutionPolicy Bypass -File "`$SCRIPT_PATH" "`$@"
  exit `$?
fi

echo "Warning: could not execute hook '$HookName' because PowerShell was not found."
exit 0
"@
    }
    else {
@"
#!/bin/bash
# Generated by scripts/Install-GitHookEnforcement.ps1
REPO_ROOT=`$(git rev-parse --show-toplevel)
SCRIPT_PATH="`$REPO_ROOT/scripts/git-hooks/$scriptName"

if [ -x "`$SCRIPT_PATH" ] || [ -f "`$SCRIPT_PATH" ]; then
  bash "`$SCRIPT_PATH" "`$@"
  exit `$?
fi

echo "Warning: hook script missing: `$SCRIPT_PATH"
exit 0
"@
    }

    Set-Content -LiteralPath $hookPath -Value $wrapper -Encoding Ascii

    if ($IsLinux -or $IsMacOS) {
        chmod +x $hookPath
    }

    Write-Host "Installed hook '$HookName' -> scripts/git-hooks/$scriptName"
}

function Remove-Hook {
    param([string]$HookName)
    $hookPath = Join-Path $HooksDir $HookName
    if (Test-Path -LiteralPath $hookPath -PathType Leaf) {
        Remove-Item -LiteralPath $hookPath -Force
        Write-Host "Removed hook '$HookName'"
    }
}

function Show-HookStatus {
    Write-Host "Git Hook Enforcement Status"
    Write-Host ""

    foreach ($hook in $HookPlan) {
        $hookPath = Join-Path $HooksDir $hook.Name
        $selected = Resolve-HookScript -Hook $hook
        $preferredPath = Join-Path $ScriptHooksDir $hook.Preferred
        $fallbackPath = Join-Path $ScriptHooksDir $hook.Fallback

        $hookInstalled = if (Test-Path -LiteralPath $hookPath -PathType Leaf) { "installed" } else { "not-installed" }
        $preferredState = if (Test-Path -LiteralPath $preferredPath -PathType Leaf) { "present" } else { "missing" }
        $fallbackState = if (Test-Path -LiteralPath $fallbackPath -PathType Leaf) { "present" } else { "missing" }
        $selectedName = if ($null -ne $selected) { [System.IO.Path]::GetFileName($selected) } else { "none" }

        Write-Host ("{0}: hook={1}, preferred={2} ({3}), fallback={4} ({5}), selected={6}" -f `
            $hook.Name, $hookInstalled, $hook.Preferred, $preferredState, $hook.Fallback, $fallbackState, $selectedName)
    }

    Write-Host ""
    Write-Host "Install:   powershell -File scripts/Install-GitHookEnforcement.ps1 -Install"
    Write-Host "Uninstall: powershell -File scripts/Install-GitHookEnforcement.ps1 -Uninstall"
}

if ($Status -or (-not $Install -and -not $Uninstall)) {
    Show-HookStatus
    exit 0
}

if ($Uninstall) {
    foreach ($hook in $HookPlan) {
        Remove-Hook -HookName $hook.Name
    }
    Write-Host "Hook enforcement uninstalled."
    exit 0
}

if ($Install) {
    foreach ($hook in $HookPlan) {
        $selected = Resolve-HookScript -Hook $hook
        if ($null -eq $selected) {
            Write-Warning "Skipped '$($hook.Name)': both preferred and fallback scripts are missing."
            continue
        }
        New-HookWrapper -HookName $hook.Name -ScriptPath $selected
    }

    Write-Host ""
    Write-Host "Hook enforcement install complete."
    Write-Host "The installer is idempotent and tolerates missing hook script targets."
    exit 0
}
