#!/usr/bin/env node
/**
 * build_doc_library.js — regenerate the Knowledge Center document library from a
 * Σ₀-grounded catalog (one Convergence Core, no sprawl).
 *
 * SOURCE OF TRUTH: data/knowledge/doc-catalog.json — a reviewed record for every
 * in-repo doc: {path, title, description, category, status, updated, grounding,
 * action, mergeInto, reason}. It is the grounding for the surface: a card is shown
 * ONLY when action === "keep", and it carries a verified description + status +
 * grounding badge (NOT a scraped first line). Docs the catalog marks
 * archive/remove/merge are dropped from the Knowledge Center (and therefore from
 * the RAG grounding index, which scrapes /repo/*.md links from this page).
 *
 * Two doc sources, one ranked surface:
 *   1. IN-REPO docs → `/repo/<path>.md` cards (scraped by build_knowledge_index.py
 *      → grounding corpus + Explore feed).
 *   2. EXTERNAL docs (Human Flourishing Frameworks) → cards that LINK to the GitHub
 *      source, driven by the COMMITTED data/knowledge/external-sources.json (we do
 *      NOT re-walk the gitignored staging dir here — that could change/leak the
 *      curated external set).
 *
 * The ENTIRE `<div class="doc-grid">` is regenerated between the AUTO markers.
 * Idempotent. CRLF-safe (the repo's docs are mostly CRLF; the old `^---\n`
 * frontmatter strip silently failed on them, leaking `author:`/`Status:` lines as
 * summaries — fixed here by normalizing newlines on read).
 *
 * Run:  node scripts/build_doc_library.js   (then: python scripts/build_knowledge_index.py)
 */
'use strict';

const fs = require('fs');
const path = require('path');

const REPO = path.resolve(__dirname, '..');
const KC_HTML = path.join(REPO, 'apps', 'lantern-garage', 'public', 'knowledgecenter.html');
const CATALOG = path.join(REPO, 'data', 'knowledge', 'doc-catalog.json');
const EXTERNAL_OUT = path.join(REPO, 'data', 'knowledge', 'external-sources.json');

const CORE = new Set(['README.md', 'CLAUDE.md', 'AGENTS.md', 'QUICKSTART.md']);

const MARK_START = '<!-- LIBRARY:AUTO:START (generated by scripts/build_doc_library.js — do not hand-edit) -->';
const MARK_END = '<!-- LIBRARY:AUTO:END -->';

// ── category presentation (data-cat must match the filter chips in the HTML) ──
const CATS = {
  guides:           { label: 'Guides',              icon: '📘', order: 2 },
  architecture:     { label: 'Architecture',        icon: '🏛️', order: 3 },
  research:         { label: 'Research',            icon: '🧪', order: 4 },
  'convergence-io': { label: 'Convergence IO',      icon: '🔭', order: 5 },
  training:         { label: 'Training & models',   icon: '🧠', order: 6 },
  trading:          { label: 'Trading',             icon: '📈', order: 7 },
  creator:          { label: 'Creator suite',       icon: '🎬', order: 8 },
  setup:            { label: 'Setup & integrations',icon: '🔌', order: 9 },
  ops:              { label: 'Operations',          icon: '⚙️', order: 10 },
  reports:          { label: 'Audits & reports',    icon: '📋', order: 11 },
  library:          { label: 'Library',             icon: '📄', order: 12 },
  lore:             { label: 'Lore',                icon: '📜', order: 13 },
};

// Essentials pinned to the front of the "All" view (independent of category).
const PIN = [
  'AGENTS.md', 'PROVIDERS.md', 'SKILLS.md', 'SECURITY.md',
  'docs/ARCHITECTURE.md', 'docs/adr/README.md', 'docs/RESEARCH-CANON.md',
  'docs/BENCHMARKS.md', 'docs/CONVERGANCE-SIGMA0-BRIEFING.md',
  'docs/MEMORY-RETRIEVAL.md', 'docs/SIGMA0-OURO-CODER.md', 'docs/SIGMA0-EV-GATE.md',
  'docs/UNISONA-1.8.md', 'docs/KEYSTONE-PRODUCT.md', 'docs/convergence-io/README.md',
];
const PIN_IDX = new Map(PIN.map((p, i) => [p, i]));

const STATUS_ORDER = { Living: 0, Reference: 1, Draft: 2, Historical: 3, Superseded: 4, Duplicate: 5, Lore: 6, Unreviewed: 7 };

// ── helpers ──────────────────────────────────────────────────────────────────
const esc = (s) => String(s).replace(/[&<>"']/g, (c) =>
  ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));

function readText(abs) {
  let md = fs.readFileSync(abs, 'utf8');
  if (md.charCodeAt(0) === 0xfeff) md = md.slice(1);
  return md.replace(/\r\n/g, '\n').replace(/\r/g, '\n');   // CRLF-safe
}

function stripFrontmatter(md) {
  const m = md.match(/^---\n[\s\S]*?\n---\n?/);
  return m ? md.slice(m[0].length) : md;
}

function prettyFromName(name) {
  return name.replace(/\.md$/i, '').replace(/[-_]/g, ' ').replace(/\s+/g, ' ').trim();
}

// Fallback extractor for docs NOT in the catalog (new since the audit). Skips
// metadata-ish lines so we don't surface `author:`/`Status:`/`Date:` as a summary.
const METAKEY = /^(author|owner|created|updated|date|status|version|scope|objective|deciders|approved[- ]?by|supersed|adr|project|severity|priority|commit|generated|tagline|driver|milestone|quality gate)\b\s*[:=]/i;
function fallbackMeta(md) {
  const body = stripFrontmatter(md);
  const lines = body.split('\n');
  let title = '', i = 0;
  for (; i < lines.length; i++) {
    const h = lines[i].match(/^#\s+(.*)/);
    if (h) { title = h[1].trim(); i++; break; }
    if (lines[i].trim()) break;
  }
  let summary = '';
  for (; i < lines.length; i++) {
    let ln = lines[i].trim();
    if (!ln || ln.startsWith('#') || ln.startsWith('>') || ln.startsWith('|') ||
        ln.startsWith('```') || ln.startsWith('![') || ln.startsWith('<')) continue;
    if (/^[-*_=]{2,}$/.test(ln)) continue;
    const bare = ln.replace(/^\*+|\*+$/g, '').replace(/`/g, '').trim();
    if (METAKEY.test(bare)) continue;                          // skip metadata lines
    summary = ln.replace(/[*_`>#\[\]]/g, '').replace(/\(https?:\/\/[^)]+\)/g, '').trim();
    if (summary && /[A-Za-z]/.test(summary) && !METAKEY.test(summary)) break;
    summary = '';
  }
  if (summary.length > 150) summary = summary.slice(0, 147).replace(/\s+\S*$/, '') + '…';
  return { title, summary };
}

function fmtDate(s) {
  if (!s) return '';
  const m = String(s).match(/(\d{4})-(\d{2})-(\d{2})/);
  if (!m) return '';
  const months = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
  return `${months[+m[2] - 1]} ${m[1]}`;
}

function walkMd(dir, rel = '') {
  const out = [];
  let entries;
  try { entries = fs.readdirSync(dir, { withFileTypes: true }); } catch { return out; }
  for (const e of entries) {
    const r = rel ? rel + '/' + e.name : e.name;
    if (e.isDirectory()) {
      if (e.name === 'archive' || e.name === 'node_modules' || e.name.startsWith('.')) continue;
      out.push(...walkMd(path.join(dir, e.name), r));
    } else if (e.isFile() && /\.md$/i.test(e.name)) out.push(r);
  }
  return out;
}

function catLabelFor(rel, cat) {
  if (rel.startsWith('docs/adr/')) return /README/i.test(rel) ? 'ADR · Index' : 'ADR';
  return (CATS[cat] && CATS[cat].label) || 'Library';
}

// ── card renderer (larger panel + metadata footer: category · status · grounding · date) ──
function card(c) {
  const cat = c.cat;
  const icon = c.icon || (CATS[cat] && CATS[cat].icon) || '📄';
  const s = c.status || 'Unreviewed';
  const g = c.grounding || '';
  const attrs = [
    `class="doc-card"`, `data-cat="${cat}"`, `data-type="${c.type || 'md'}"`,
    `data-status="${s.toLowerCase()}"`, g ? `data-grounding="${g.toLowerCase()}"` : '',
    `href="${esc(c.href)}"`, c.external ? 'target="_blank" rel="noopener"' : '',
  ].filter(Boolean).join(' ');
  const badges = [
    `<span class="doc-badge b-status" data-s="${s.toLowerCase()}">${esc(s)}</span>`,
    g ? `<span class="doc-badge b-ground" data-g="${g.toLowerCase()}">${esc(g)}</span>` : '',
  ].filter(Boolean).join('');
  const extBadge = c.external ? '<span class="doc-ext">↗ HFF</span>' : '';
  const date = c.date ? `<span class="doc-date">${esc(c.date)}</span>` : '';
  return [
    `      <a ${attrs}>`,
    `        <span class="doc-top"><span class="doc-ico">${icon}</span><span class="doc-fmt">${esc(c.fmt || 'MD')}</span></span>`,
    `        <span class="doc-title">${esc(c.title)}</span>`,
    `        <span class="doc-sum">${esc(c.summary)}</span>`,
    `        <span class="doc-foot"><span class="doc-cat">${esc(c.catLabel)}${extBadge}</span>${badges}${date}</span>`,
    `      </a>`,
  ].join('\n');
}

// ── 1. in-repo docs from the catalog ──────────────────────────────────────────
function inRepoCards() {
  let catalog = [];
  try { catalog = JSON.parse(fs.readFileSync(CATALOG, 'utf8')); } catch (e) {
    throw new Error('doc-catalog.json missing or invalid — run the audit first: ' + e.message);
  }
  const byPath = new Map(catalog.map((e) => [e.path, e]));
  const onDisk = [
    ...fs.readdirSync(REPO).filter((f) => /\.md$/i.test(f)),
    ...walkMd(path.join(REPO, 'docs'), 'docs'),
    ...walkMd(path.join(REPO, 'lore'), 'lore'),
  ];
  const seen = new Set();
  const entries = [];
  const stats = { keep: 0, excluded: 0, unreviewed: 0, missing: 0 };
  for (const rel of onDisk) {
    if (seen.has(rel)) continue;
    seen.add(rel);
    // CORE docs are always grounded by build_knowledge_index.py; skip them here
    // UNLESS the catalog explicitly surfaces one as a card (e.g. AGENTS.md).
    if (CORE.has(rel) && !byPath.has(rel)) continue;
    const e = byPath.get(rel);
    if (e) {
      if (e.action !== 'keep') { stats.excluded++; continue; }
      const cat = CATS[e.category] ? e.category : 'library';
      entries.push({
        rel, cat, icon: e.icon,
        catLabel: catLabelFor(rel, cat),
        title: e.title || prettyFromName(path.basename(rel)),
        summary: e.description || `Reference doc · ${rel}`,
        status: e.status || 'Reference',
        grounding: e.grounding || '',
        date: fmtDate(e.updated),
        pin: PIN_IDX.has(rel) ? PIN_IDX.get(rel) : 999,
      });
      stats.keep++;
    } else {
      // uncatalogued → fallback extraction, flagged Unreviewed
      const { title, summary } = fallbackMeta(readText(path.join(REPO, rel)));
      const cat = 'library';
      entries.push({
        rel, cat, catLabel: catLabelFor(rel, cat),
        title: title || prettyFromName(path.basename(rel)),
        summary: summary || `Reference doc · ${rel}`,
        status: 'Unreviewed', grounding: '', date: '',
        pin: 999,
      });
      stats.unreviewed++;
    }
  }
  // catalog entries whose file is gone
  for (const e of catalog) if (!seen.has(e.path) && !CORE.has(e.path)) stats.missing++;

  // sort: pinned first, then category order, then status, then title
  entries.sort((a, b) =>
    a.pin - b.pin ||
    ((CATS[a.cat] && CATS[a.cat].order) || 99) - ((CATS[b.cat] && CATS[b.cat].order) || 99) ||
    (STATUS_ORDER[a.status] ?? 9) - (STATUS_ORDER[b.status] ?? 9) ||
    a.title.localeCompare(b.title));

  const cards = entries.map((e) => card({
    cat: e.cat, href: '/repo/' + e.rel, icon: e.icon, title: e.title,
    summary: e.summary, catLabel: e.catLabel, status: e.status,
    grounding: e.grounding, date: e.date,
  }));
  return { cards, stats };
}

// ── 2. external HFF docs from the COMMITTED manifest (no staging re-walk) ──────
function hffCards() {
  let manifest = [];
  try { manifest = JSON.parse(fs.readFileSync(EXTERNAL_OUT, 'utf8')); } catch { return { cards: [] }; }
  const cards = manifest
    .filter((e) => e && e.doc && e.url)
    .map((e) => card({
      cat: 'hff', href: e.url, external: true, icon: '🌍',
      title: e.title || prettyFromName(e.doc.split('/').pop()),
      summary: e.description || `Human Flourishing Frameworks · ${e.doc.replace(/^hff\//, '')}`,
      catLabel: 'Convergence · HFF',
      status: e.status || 'Reference', grounding: e.grounding || 'Ungrounded',
      date: fmtDate(e.updated),
    }));
  return { cards };
}

// ── main ──────────────────────────────────────────────────────────────────────
function main() {
  let html = fs.readFileSync(KC_HTML, 'utf8');
  const repo = inRepoCards();
  const hff = hffCards();

  const block = [
    MARK_START,
    '      <!-- In-repo library (catalog-driven; scraped by build_knowledge_index.py → grounding corpus + Explore) -->',
    repo.cards.join('\n'),
    '',
    '      <!-- External: Human Flourishing Frameworks (committed external-sources.json; links to GitHub source) -->',
    hff.cards.join('\n'),
    '      ' + MARK_END,
  ].join('\n');

  const reAuto = new RegExp(
    MARK_START.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') + '[\\s\\S]*?' +
    MARK_END.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'));
  if (!reAuto.test(html)) throw new Error('AUTO markers not found in knowledgecenter.html');
  html = html.replace(reAuto, block);

  fs.writeFileSync(KC_HTML, html, 'utf8');
  console.log(`doc library: ${repo.cards.length} in-repo cards (keep=${repo.stats.keep}, ` +
    `excluded=${repo.stats.excluded}, unreviewed=${repo.stats.unreviewed}, missing=${repo.stats.missing}), ` +
    `${hff.cards.length} HFF cards`);
  console.log('  next: python scripts/build_knowledge_index.py');
}

main();
