#!/usr/bin/env node
/**
 * build_doc_library.js — expand the Knowledge Center into the full curated library.
 *
 * Two doc sources, one ranked surface (Σ₀ "one Convergence Core, no sprawl"):
 *
 *   1. IN-REPO docs (lantern-os): emitted as `/repo/<path>.md` cards into
 *      knowledgecenter.html. build_knowledge_index.py scrapes those links, so they
 *      are FULLY ingested into the grounding corpus (RAG) and auto-appear in the
 *      Explore feed via lib/explore-feed.js docCards().
 *
 *   2. EXTERNAL docs (Human Flourishing Frameworks): pulled via `gh` into the
 *      gitignored staging dir (data/ingest-staging/hff/). We surface them as cards
 *      that LINK to the GitHub source (formatted there) and register them in
 *      data/knowledge/external-sources.json so they show in KC + Explore — but we
 *      do NOT copy their text into the committed grounding index (the staging
 *      decision: nothing about HFF is committed to lantern-os git).
 *
 * Idempotent: rewrites the region between the AUTO markers each run.
 *
 * Run:  node scripts/build_doc_library.js
 */
'use strict';

const fs = require('fs');
const path = require('path');

const REPO = path.resolve(__dirname, '..');
const KC_HTML = path.join(REPO, 'apps', 'lantern-garage', 'public', 'knowledgecenter.html');
const HFF_STAGE = path.join(REPO, 'data', 'ingest-staging', 'hff');
const EXTERNAL_OUT = path.join(REPO, 'data', 'knowledge', 'external-sources.json');

const HFF_BLOB = 'https://github.com/human-flourishing-frameworks/human-flourishing-frameworks/blob/master/';

const CORE = new Set(['README.md', 'CLAUDE.md', 'AGENTS.md', 'QUICKSTART.md']);

const MARK_START = '<!-- LIBRARY:AUTO:START (generated by scripts/build_doc_library.js — do not hand-edit) -->';
const MARK_END = '<!-- LIBRARY:AUTO:END -->';

// ── helpers ──────────────────────────────────────────────────────────────────
const esc = (s) => String(s).replace(/[&<>"']/g, (c) =>
  ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));

function stripFrontmatter(md) {
  if (md.charCodeAt(0) === 0xfeff) md = md.slice(1);
  const m = md.match(/^---\n[\s\S]*?\n---\n?/);
  return m ? md.slice(m[0].length) : md;
}

function prettyFromName(name) {
  return name.replace(/\.md$/i, '').replace(/[-_]/g, ' ')
    .replace(/\s+/g, ' ').trim();
}

/** Extract a {title, summary} from markdown text. */
function meta(md) {
  const body = stripFrontmatter(md);
  const lines = body.split('\n');
  let title = '';
  let i = 0;
  for (; i < lines.length; i++) {
    const h = lines[i].match(/^#\s+(.*)/);
    if (h) { title = h[1].trim(); i++; break; }
    if (lines[i].trim()) break; // first non-blank non-h1 line: no title heading
  }
  // first non-empty, non-heading, non-blockquote paragraph as summary
  let summary = '';
  for (; i < lines.length; i++) {
    const ln = lines[i].trim();
    if (!ln || ln.startsWith('#') || ln.startsWith('>') || ln.startsWith('|') ||
        ln.startsWith('```') || ln.startsWith('![') || ln.startsWith('<')) continue;
    if (/^[-*_=]{2,}$/.test(ln)) continue;          // horizontal rules / frontmatter fences
    summary = ln.replace(/[*_`>#\[\]]/g, '').replace(/\(https?:\/\/[^)]+\)/g, '').trim();
    if (summary && /[A-Za-z]/.test(summary)) break;  // need real prose, not punctuation
    summary = '';
  }
  if (summary.length > 150) summary = summary.slice(0, 147).replace(/\s+\S*$/, '') + '…';
  return { title, summary };
}

function walkMd(dir, rel = '') {
  const out = [];
  let entries;
  try { entries = fs.readdirSync(dir, { withFileTypes: true }); } catch { return out; }
  for (const e of entries) {
    const r = rel ? rel + '/' + e.name : e.name;
    if (e.isDirectory()) {
      if (e.name === 'archive' || e.name === 'node_modules' || e.name.startsWith('.')) continue;
      out.push(...walkMd(path.join(dir, e.name), r));
    } else if (e.isFile() && /\.md$/i.test(e.name)) {
      out.push(r);
    }
  }
  return out;
}

// Categorize a doc into one filter bucket. Structural (path-based) rules win
// first; the former 144-doc "Library" catch-all is then split into balanced
// TOPICAL buckets keyed on the filename so no single chip dominates the library.
// Keyword order matters: more specific intent (audits/reports) is tested before
// broad domain terms so e.g. "TRADING-VALIDATION" lands under reports, not trading.
function categorize(rel) {
  if (rel.startsWith('docs/adr/')) return ['architecture', 'ADR'];
  if (rel.startsWith('docs/convergence-io/')) return ['convergence-io', 'Convergence IO'];
  if (rel.startsWith('docs/research/')) return ['research', 'Research'];
  if (/SIGMA0|TESSERACT|RESEARCH-CANON|CONVERGANCE|convergence/i.test(rel)) return ['research', 'Research'];
  if (rel.startsWith('lore/')) return ['lore', 'Lore'];

  const base = rel.split('/').pop().toUpperCase();

  // Audits, reports, QA, validations, reviews, readiness checks
  if (/AUDIT|REPORT|SUMMARY|[-_]QA\b|\bQA[-_]|VALIDATION|FEATURE-TEST|READINESS|REVIEW/.test(base))
    return ['reports', 'Audits & reports'];
  // Trading & markets
  if (/TRADER|TRADING|KALSHI|IBKR|PORTFOLIO|PREDICTION-MARKET|MARKET/.test(base))
    return ['trading', 'Trading'];
  // Training & models
  if (/OURO|TRAINING|SERVING|GPU|LOOPLM|DATASET|MULTISOURCE/.test(base))
    return ['training', 'Training & models'];
  // Creator suite (studio, video, uploads, the v10 viral pipeline)
  if (/CREATOR|FACECAM|THREE-DOORS|UPLOAD|JOURNAL_UPLOAD|V10|VIRAL|EDITOR/.test(base))
    return ['creator', 'Creator suite'];
  // Setup & integrations (provider/API hookups, deploys, connectors)
  if (/SETUP|CONNECTOR|OAUTH|DEPLOY|TUNNEL|API-SPEC|API-REFERENCE|MCP|YOUTUBE|MEDIA-HOSTING|CLOUDFLARE|HOSTING|PATREON/.test(base))
    return ['setup', 'Setup & integrations'];
  // Operations (workflow, repo process, runbooks, governance, CI/CD)
  if (/MONOWORKSTREAM|ROLLOVER|REPO-CONTRACT|MERGE|WORK-?QUEUE|RUNBOOK|CICD|RUNTIME|BACKLOG|DISPATCH|SCRIPTS|PII|GOVERNANCE|PRIVACY|HANDOFF|QUEUE|STANDARDS|SITEMAP|CODEMAP/.test(base))
    return ['ops', 'Operations'];

  return ['library', 'Library'];
}

const ICON = {
  architecture: '🏛️', 'convergence-io': '🔭', research: '🧪', library: '📄', hff: '🌍',
  setup: '🔌', trading: '📈', training: '🧠', creator: '🎬', ops: '⚙️', reports: '📋', lore: '📜',
};

function card({ cat, type = 'md', href, external = false, icon, title, summary, catLabel, fmt = 'MD' }) {
  const ext = external
    ? ' target="_blank" rel="noopener"'
    : '';
  const badge = external ? '<span class="doc-ext">↗ HFF</span>' : '';
  return [
    `      <a class="doc-card" data-cat="${cat}" data-type="${type}" href="${esc(href)}"${ext}>`,
    `        <span class="doc-ico">${icon}</span>`,
    `        <span class="doc-body"><span class="doc-title">${esc(title)}</span><span class="doc-sum">${esc(summary)}</span></span>`,
    `        <span class="doc-meta"><span class="doc-cat">${esc(catLabel)}${badge}</span><span class="doc-fmt">${fmt}</span></span>`,
    `      </a>`,
  ].join('\n');
}

// ── 1. in-repo curated docs ───────────────────────────────────────────────────
function inRepoDocs(existing) {
  const candidates = [
    ...fs.readdirSync(REPO).filter((f) => /\.md$/i.test(f)),          // root *.md
    ...walkMd(path.join(REPO, 'docs'), 'docs'),                       // docs/** (no archive)
    ...walkMd(path.join(REPO, 'lore'), 'lore'),                       // lore/**
  ];
  const seen = new Set();
  const cards = [];
  let n = 0;
  for (const rel of candidates) {
    if (seen.has(rel)) continue;
    seen.add(rel);
    if (CORE.has(rel)) continue;            // already core-indexed + featured
    if (existing.has(rel)) continue;        // already a hand-curated featured card
    const abs = path.join(REPO, rel);
    let md = '';
    try { md = fs.readFileSync(abs, 'utf8'); } catch { continue; }
    const { title, summary } = meta(md);
    const [cat, catLabel] = categorize(rel);
    cards.push(card({
      cat, href: '/repo/' + rel, icon: ICON[cat] || '📄',
      title: title || prettyFromName(path.basename(rel)),
      summary: summary || `Reference doc · ${rel}`,
      catLabel,
    }));
    n++;
  }
  return { cards, n };
}

// ── 2. external HFF docs (staging → cards + manifest, no committed text) ───────
function hffDocs() {
  const cards = [];
  const manifest = [];
  let files = [];
  try { files = fs.readdirSync(HFF_STAGE).filter((f) => /\.md$/i.test(f)); } catch { return { cards, manifest, n: 0 }; }
  for (const fname of files.sort()) {
    const origPath = fname.replace(/__/g, '/');         // staging encodes '/' as '__'
    const abs = path.join(HFF_STAGE, fname);
    let md = '';
    try { md = fs.readFileSync(abs, 'utf8'); } catch { continue; }
    const { title, summary } = meta(md);
    const url = HFF_BLOB + origPath;
    const docTitle = title || prettyFromName(path.basename(origPath));
    cards.push(card({
      cat: 'hff', href: url, external: true, icon: ICON.hff,
      title: docTitle,
      summary: summary || `Human Flourishing Frameworks · ${origPath}`,
      catLabel: 'Convergence · HFF',
    }));
    manifest.push({
      doc: 'hff/' + origPath,
      title: docTitle,
      url,
      source: 'Human Flourishing Frameworks',
      topics: ['convergence', 'flourishing', 'research'],
    });
  }
  return { cards, manifest, n: cards.length };
}

// ── main ──────────────────────────────────────────────────────────────────────
function main() {
  let html = fs.readFileSync(KC_HTML, 'utf8');

  // docs already hand-linked as FEATURED cards — don't duplicate them. Exclude the
  // auto-region first, else a re-run treats its own injected links as "existing"
  // and wipes them (idempotency).
  const reAuto = new RegExp(
    MARK_START.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') + '[\\s\\S]*?' +
    MARK_END.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'));
  const htmlFeatured = html.replace(reAuto, '');
  const existing = new Set();
  for (const m of htmlFeatured.matchAll(/href="\/repo\/([^"]+\.md)"/g)) existing.add(m[1]);

  const repo = inRepoDocs(existing);
  const hff = hffDocs();

  // write the external-sources manifest (consumed by build_knowledge_index.py +
  // lib/explore-feed.js — surfaced as cards, content NOT committed to the index)
  fs.mkdirSync(path.dirname(EXTERNAL_OUT), { recursive: true });
  fs.writeFileSync(EXTERNAL_OUT, JSON.stringify(hff.manifest, null, 2) + '\n', 'utf8');

  const block = [
    MARK_START,
    '      <!-- In-repo curated library (auto): scraped by build_knowledge_index.py → grounding corpus + Explore -->',
    repo.cards.join('\n'),
    '',
    '      <!-- External: Human Flourishing Frameworks (link to GitHub source; registered in external-sources.json) -->',
    hff.cards.join('\n'),
    '      ' + MARK_END,
  ].join('\n');

  // inject before the Reports comment / grid close
  if (html.includes(MARK_START)) {
    html = html.replace(new RegExp(MARK_START.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') + '[\\s\\S]*?' + MARK_END.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')), block);
  } else {
    const anchor = '      <!-- Reports (PDFs) are injected here from /api/pdfs -->';
    if (!html.includes(anchor)) throw new Error('anchor comment not found in knowledgecenter.html');
    html = html.replace(anchor, block + '\n\n' + anchor);
  }

  // ensure the two new filter chips exist
  if (!/data-cat="library"/.test(html)) {
    html = html.replace(
      '<button class="chip" data-cat="reports">Reports</button>',
      '<button class="chip" data-cat="library">Library</button>\n' +
      '      <button class="chip" data-cat="hff">Convergence (HFF)</button>\n' +
      '      <button class="chip" data-cat="reports">Reports</button>'
    );
  }

  fs.writeFileSync(KC_HTML, html, 'utf8');
  console.log(`doc library: +${repo.n} in-repo cards, +${hff.n} HFF cards`);
  console.log(`  external-sources.json: ${hff.manifest.length} entries -> ${path.relative(REPO, EXTERNAL_OUT)}`);
  console.log('  next: python scripts/build_knowledge_index.py');
}

main();
