# Auto-generated by Start-Lantern.ps1 -RegisterAutostart - DO NOT EDIT
Set-Location "C:\dev\lantern-os"
New-Item -ItemType Directory -Force -Path "C:\dev\lantern-os\logs" | Out-Null
$log = "C:\dev\lantern-os\logs\cloudflare-autostart.log"
"[$(Get-Date -Format 'u')] Cloudflare tunnel autostart triggered" | Tee-Object -Append $log

$cloudflared = Get-Command cloudflared -ErrorAction SilentlyContinue
if (-not $cloudflared) {
    "[$(Get-Date -Format 'u')] ERROR: cloudflared not found - install with: winget install Cloudflare.cloudflared" | Tee-Object -Append $log
    exit 1
}

# Use the system cloudflared config (~/.cloudflared/config.yml) which has the correct
# tunnel ID (16689f09-...) and credentials-file path already set by 'cloudflared tunnel login'
$cfConfig = "$env:USERPROFILE\.cloudflared\config.yml"
if (-not (Test-Path $cfConfig)) {
    "[$(Get-Date -Format 'u')] ERROR: No cloudflared config at $cfConfig - run: cloudflared tunnel login && cloudflared tunnel create lantern-os" | Tee-Object -Append $log
    exit 1
}

# Watchdog loop - cloudflared exits on network loss; restart with short backoff
while ($true) {
    "[$(Get-Date -Format 'u')] Starting cloudflared tunnel" | Tee-Object -Append $log
    & cloudflared tunnel --config "$cfConfig" run 2>&1 | Tee-Object -Append $log
    "[$(Get-Date -Format 'u')] cloudflared exited (code $LASTEXITCODE) - restarting in 5s" | Tee-Object -Append $log
    Start-Sleep -Seconds 5
}
