# Auto-generated by Start-Lantern.ps1 -RegisterAutostart - DO NOT EDIT
Set-Location "C:\dev\lantern-os"
New-Item -ItemType Directory -Force -Path "C:\dev\lantern-os\logs" | Out-Null
$log = "C:\dev\lantern-os\logs\discord-autostart.log"
"[$(Get-Date -Format 'u')] Discord bot autostart triggered" | Tee-Object -Append $log

# Load env - check .env.local first, then .env
foreach ($envFile in @("C:\dev\lantern-os\.env.local", "C:\dev\lantern-os\.env")) {
    if (Test-Path $envFile) {
        Get-Content $envFile | ForEach-Object {
            $line = $_.Trim()
            if ($line -and !$line.StartsWith('#') -and $line.Contains('=')) {
                $parts = $line.Split('=', 2)
                $k = $parts[0].Trim(); $v = $parts[1].Trim()
                if ($k -and -not [Environment]::GetEnvironmentVariable($k)) {
                    [Environment]::SetEnvironmentVariable($k, $v)
                }
            }
        }
        break
    }
}

# Verify token is available before launching
$token = [Environment]::GetEnvironmentVariable('DISCORD_BOT_TOKEN')
if (-not $token) {
    "[$(Get-Date -Format 'u')] ERROR: DISCORD_BOT_TOKEN not set - bot not started" | Tee-Object -Append $log
    exit 1
}

# Watchdog loop - restart bot on crash with 10s backoff
$pythonExe = if (Test-Path "C:\dev\lantern-os\.venv\Scripts\python.exe") { "C:\dev\lantern-os\.venv\Scripts\python.exe" } else { "python" }
while ($true) {
    "[$(Get-Date -Format 'u')] Starting Discord bot" | Tee-Object -Append $log
    & $pythonExe "C:\dev\lantern-os\src\discord_lounge_bot\bot_v2.py" 2>&1 | Tee-Object -Append $log
    "[$(Get-Date -Format 'u')] Bot exited (code $LASTEXITCODE) - restarting in 10s" | Tee-Object -Append $log
    Start-Sleep -Seconds 10
}
