param(
    [string]$TemplatePath = "D:\tmp\lantern-os\templates\evidence\recovery-test-receipt-template.md",
    [string]$OutputDir = "D:\tmp\lantern-os\manifests\evidence",
    [string]$ReceiptType = "automated-action",
    [hashtable]$ReceiptData = @{},
    [switch]$Generate,
    [switch]$RunOnce
)

$ErrorActionPreference = "Stop"

function Write-Log {
    param([string]$Message, [string]$Level = "INFO")
    $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    Write-Host "[$timestamp] [$Level] $Message"
    $logPath = "D:\tmp\lantern-os\data\automation\receipt-generator.log"
    Add-Content -Path $logPath -Value "[$timestamp] [$Level] $Message" -ErrorAction SilentlyContinue
}

function Get-ReceiptTemplate {
    param([string]$Type)
    
    $templates = @{
        "automated-action" = @{
            title = "Automated Action Receipt"
            sections = @("Action Description", "Evidence", "Validation", "Rollback Path", "Operator Approval")
        }
        "mcp-canary" = @{
            title = "MCP Canary Test Receipt"
            sections = @("Test Scope", "Results", "Safety Verification", "Next Steps")
        }
        "outreach-send" = @{
            title = "Outreach Send Receipt"
            sections = @("Recipient", "Message", "Platform", "Follow-up Action")
        }
        "paid-pilot" = @{
            title = "Paid Pilot Receipt"
            sections = @("Client", "Scope", "Payment", "Deliverables", "Evidence")
        }
        "demo-execution" = @{
            title = "Demo Execution Receipt"
            sections = @("Demo Scope", "Participants", "Results", "Feedback", "Next Action")
        }
    }
    
    return $templates[$Type]
}

function New-Receipt {
    param(
        [string]$Type,
        [hashtable]$Data
    )
    
    $template = Get-ReceiptTemplate -Type $Type
    $timestamp = Get-Date -Format "yyyy-MM-ddTHH:mm:ss"
    $date = Get-Date -Format "yyyy-MM-dd"
    $receiptId = "RECEIPT-$date-$(Get-Random -Minimum 1000 -Maximum 9999)"
    
    $content = @"
# $($template.title)

**Receipt ID:** $receiptId  
**Generated:** $timestamp  
**Type:** $Type  
**Status:** $(if ($Data.Status) { $Data.Status } else { "pending-validation" })

---

## Simple Answer

$(if ($Data.Summary) { $Data.Summary } else { "Automated action executed with validation pending." })

---

## What It Actually Does

$(if ($Data.Description) { $Data.Description } else { "This receipt documents an automated or semi-automated action taken by the Lantern OS fleet." })

---

## Evidence / Source Discipline

$(if ($Data.Evidence) { $Data.Evidence } else { "- Action logged at: $timestamp" })
- Source system: $(if ($Data.Source) { $Data.Source } else { "Lantern OS Automation" })
- Validation state: $(if ($Data.Validation) { $Data.Validation } else { "unvalidated" })

---

## Proven / Held / Local-Only

**Proven:**
$(if ($Data.Proven) { $Data.Proven } else { "- Receipt generated" })

**Held:**
$(if ($Data.Held) { $Data.Held } else { "- Awaiting operator review" })

**Local-Only:**
$(if ($Data.LocalOnly) { $Data.LocalOnly } else { "- This receipt is local evidence only" })

---

## Next Safe Action

$(if ($Data.NextAction) { $Data.NextAction } else { "1. Review this receipt`n2. Validate evidence`n3. Update confidence scores if appropriate" })

---

## Validation Path

- [ ] Operator review completed
- [ ] Evidence verified
- [ ] Confidence updated
- [ ] Receipt archived

---

## Rollback (if needed)

$(if ($Data.Rollback) { $Data.Rollback } else { "Revert to state before $timestamp if validation fails." })

---

*Generated by Lantern OS Receipt Generator*  
*Template: $Type*
"@
    
    return @{
        id = $receiptId
        content = $content
        filename = "$receiptId-$Type.md"
        type = $Type
        generatedAt = $timestamp
    }
}

function Invoke-ReceiptGenerator {
    Write-Log "=== Receipt Generator Started ==="
    
    if ($Generate) {
        Write-Log "Generating receipt: $ReceiptType"
        
        $receipt = New-Receipt -Type $ReceiptType -Data $ReceiptData
        
        $outputPath = Join-Path $OutputDir $receipt.filename
        
        if (-not (Test-Path $OutputDir)) {
            New-Item -ItemType Directory -Path $OutputDir -Force | Out-Null
        }
        
        $receipt.content | Set-Content $outputPath
        
        Write-Log "Receipt saved to: $outputPath"
        
        return @{
            success = $true
            receiptId = $receipt.id
            filename = $receipt.filename
            path = $outputPath
            type = $ReceiptType
            generatedAt = $receipt.generatedAt
        }
    }
    else {
        Write-Log "Receipt generation not requested. Use -Generate to create a receipt."
        
        # Show available templates
        $templates = Get-ReceiptTemplate -Type "automated-action"
        
        return @{
            success = $false
            reason = "Generation not requested"
            availableTypes = @("automated-action", "mcp-canary", "outreach-send", "paid-pilot", "demo-execution")
            usage = "Invoke-ReceiptGenerator -Generate -ReceiptType <type> -ReceiptData @{ Summary='...'; Description='...' }"
        }
    }
}

if ($RunOnce -or -not $RunOnce) {
    Invoke-ReceiptGenerator
}
