# Auto-generated by Start-Lantern.ps1 -RegisterAutostart - DO NOT EDIT
Set-Location "C:\dev\lantern-os"
New-Item -ItemType Directory -Force -Path "C:\dev\lantern-os\logs" | Out-Null
$log = "C:\dev\lantern-os\logs\lantern-autostart.log"
"[$(Get-Date -Format 'u')] Lantern server autostart triggered" | Tee-Object -Append $log
# git pull → HFF seed → node --watch (node --watch auto-restarts on file changes)
npm run start:master --prefix "C:\dev\lantern-os\apps\lantern-garage" 2>&1 | Tee-Object -Append $log
