# Lantern OS Auto-Start (Simple version, Windows PowerShell 5.1 compatible)
# This script is generated by the autostart setup and runs on system boot/login

Set-Location "C:\dev\lantern-os"
New-Item -ItemType Directory -Force -Path "logs" | Out-Null

$logFile = "logs\lantern-autostart.log"
$timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"

"[$timestamp] [START] Lantern OS autostart triggered" | Add-Content $logFile

try {
    # Update from master
    "[$timestamp] [GIT] Pulling from origin/master..." | Add-Content $logFile
    git pull origin master 2>&1 | Add-Content $logFile

    if ($LASTEXITCODE -ne 0) {
        throw "Git pull failed"
    }

    # Start server (auto-watches for file changes)
    "[$timestamp] [SERVER] Starting Lantern Garage server..." | Add-Content $logFile
    npm start --prefix apps/lantern-garage 2>&1 | Add-Content $logFile
}
catch {
    $error_msg = $_.Exception.Message
    "[$(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')] [ERROR] $error_msg" | Add-Content $logFile
    exit 1
}

"[$(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')] [DONE] Lantern OS startup complete" | Add-Content $logFile
