#Requires -Version 5.0
<#
.SYNOPSIS
    Start all Lantern OS services.
.DESCRIPTION
    Starts Lantern Garage (Dream Journal) on port 4177.
    Optionally starts MCP server on port 8771.
    Run with -RegisterAutostart to create a Windows Task Scheduler entry.
.PARAMETER LanternRoot
    Path to lantern-os repo. Defaults to current directory.
.PARAMETER MCP
    Also start the MCP server on port 8771.
.PARAMETER RegisterAutostart
    Register Lantern Garage as a Windows login autostart task (requires Admin).
.PARAMETER UnregisterAutostart
    Remove the autostart task.
.EXAMPLE
    .\scripts\Start-Lantern.ps1
.EXAMPLE
    .\scripts\Start-Lantern.ps1 -MCP
.EXAMPLE
    .\scripts\Start-Lantern.ps1 -RegisterAutostart
#>
param(
    [string]$LanternRoot = (Get-Location).Path,
    [switch]$MCP,
    [switch]$RegisterAutostart,
    [switch]$UnregisterAutostart
)

$ErrorActionPreference = "Stop"
$TaskName          = "LanternDreamJournal"
$TaskNameDiscord   = "LanternDiscordBot"
$TaskNameCloudflare = "LanternCloudflareTunnel"

function Write-Step($msg) { Write-Host "  $msg" -ForegroundColor Cyan }
function Write-OK($msg)   { Write-Host "  [OK] $msg" -ForegroundColor Green }
function Write-Warn($msg) { Write-Host "  [WARN] $msg" -ForegroundColor Yellow }
function Write-Err($msg)  { Write-Host "  [ERR] $msg" -ForegroundColor Red }

# ── Autostart registration ─────────────────────────────────────────────────

if ($UnregisterAutostart) {
    foreach ($t in @($TaskName, $TaskNameDiscord, $TaskNameCloudflare)) {
        if (Get-ScheduledTask -TaskName $t -ErrorAction SilentlyContinue) {
            Unregister-ScheduledTask -TaskName $t -Confirm:$false
            Write-OK "Autostart task '$t' removed."
        } else {
            Write-Warn "No autostart task named '$t' found."
        }
    }
    exit 0
}

if ($RegisterAutostart) {
    $garageDir = Join-Path $LanternRoot "apps\lantern-garage"
    $logDir    = Join-Path $LanternRoot "logs"

    $pwshCmd = Get-Command pwsh -ErrorAction SilentlyContinue
    $psExe = if ($pwshCmd) { $pwshCmd.Source } else { (Get-Command powershell -ErrorAction Stop).Source }

    # ── Helper: register one task ──────────────────────────────────────────
    function Register-LanternTask {
        param(
            [string]$Name,
            [string]$WrapperPath,
            [string]$WrapperContent,
            [int]$DelaySeconds = 0
        )
        $WrapperContent | Set-Content -Path $WrapperPath -Encoding UTF8

        $action = New-ScheduledTaskAction `
            -Execute $psExe `
            -Argument "-NonInteractive -ExecutionPolicy Bypass -File `"$WrapperPath`"" `
            -WorkingDirectory $LanternRoot

        $triggerBoot  = New-ScheduledTaskTrigger -AtStartup
        $triggerLogon = New-ScheduledTaskTrigger -AtLogon

        # Boot trigger delay so the network is up before tunnels/bots start
        if ($DelaySeconds -gt 0) {
            $triggerBoot.Delay  = "PT${DelaySeconds}S"
            $triggerLogon.Delay = "PT${DelaySeconds}S"
        }

        $settings = New-ScheduledTaskSettingsSet `
            -ExecutionTimeLimit (New-TimeSpan -Hours 0) `
            -RestartCount 999 `
            -RestartInterval (New-TimeSpan -Minutes 1) `
            -MultipleInstances IgnoreNew

        Register-ScheduledTask `
            -TaskName $Name `
            -Action $action `
            -Trigger @($triggerBoot, $triggerLogon) `
            -Settings $settings `
            -RunLevel Highest `
            -Force | Out-Null

        Write-OK "Registered: '$Name'"
    }

    # ── 1. Lantern Garage server ───────────────────────────────────────────
    $serverWrapper = Join-Path $LanternRoot "scripts\lantern-autostart.ps1"
    Register-LanternTask -Name $TaskName -WrapperPath $serverWrapper -WrapperContent @"
# Auto-generated by Start-Lantern.ps1 -RegisterAutostart - DO NOT EDIT
Set-Location "$LanternRoot"
New-Item -ItemType Directory -Force -Path "$logDir" | Out-Null
`$log = "$logDir\lantern-autostart.log"
"[`$(Get-Date -Format 'u')] Lantern server autostart triggered" | Tee-Object -Append `$log
# git pull → HFF seed → node --watch (node --watch auto-restarts on file changes)
npm run start:master --prefix "$garageDir" 2>&1 | Tee-Object -Append `$log
"@

    # ── 2. Discord bot watchdog ────────────────────────────────────────────
    $discordWrapper = Join-Path $LanternRoot "scripts\discord-autostart.ps1"
    $venvPython     = Join-Path $LanternRoot ".venv\Scripts\python.exe"
    $botScript      = Join-Path $LanternRoot "src\discord_lounge_bot\bot_v2.py"
    # Fall back to system python if venv isn't built yet
    $pythonExe = if (Test-Path $venvPython) { $venvPython } else { "python" }

    Register-LanternTask -Name $TaskNameDiscord -WrapperPath $discordWrapper -DelaySeconds 30 -WrapperContent @"
# Auto-generated by Start-Lantern.ps1 -RegisterAutostart - DO NOT EDIT
Set-Location "$LanternRoot"
New-Item -ItemType Directory -Force -Path "$logDir" | Out-Null
`$log = "$logDir\discord-autostart.log"
"[`$(Get-Date -Format 'u')] Discord bot autostart triggered" | Tee-Object -Append `$log

# Load env - check .env.local first, then .env
foreach (`$envFile in @("$LanternRoot\.env.local", "$LanternRoot\.env")) {
    if (Test-Path `$envFile) {
        Get-Content `$envFile | ForEach-Object {
            `$line = `$_.Trim()
            if (`$line -and !`$line.StartsWith('#') -and `$line.Contains('=')) {
                `$parts = `$line.Split('=', 2)
                `$k = `$parts[0].Trim(); `$v = `$parts[1].Trim()
                if (`$k -and -not [Environment]::GetEnvironmentVariable(`$k)) {
                    [Environment]::SetEnvironmentVariable(`$k, `$v)
                }
            }
        }
        break
    }
}

# Verify token is available before launching
`$token = [Environment]::GetEnvironmentVariable('DISCORD_BOT_TOKEN')
if (-not `$token) {
    "[`$(Get-Date -Format 'u')] ERROR: DISCORD_BOT_TOKEN not set - bot not started" | Tee-Object -Append `$log
    exit 1
}

# Watchdog loop - restart bot on crash with 10s backoff
`$pythonExe = if (Test-Path "$venvPython") { "$venvPython" } else { "python" }
while (`$true) {
    "[`$(Get-Date -Format 'u')] Starting Discord bot" | Tee-Object -Append `$log
    & `$pythonExe "$botScript" 2>&1 | Tee-Object -Append `$log
    "[`$(Get-Date -Format 'u')] Bot exited (code `$LASTEXITCODE) - restarting in 10s" | Tee-Object -Append `$log
    Start-Sleep -Seconds 10
}
"@

    # ── 3. Cloudflare tunnel ───────────────────────────────────────────────
    $cfWrapper    = Join-Path $LanternRoot "scripts\cloudflare-autostart.ps1"
    $cfConfig     = Join-Path $LanternRoot "cloudflare-config.yml"
    $cfCredDir    = "$env:USERPROFILE\.cloudflare"

    Register-LanternTask -Name $TaskNameCloudflare -WrapperPath $cfWrapper -DelaySeconds 20 -WrapperContent @"
# Auto-generated by Start-Lantern.ps1 -RegisterAutostart - DO NOT EDIT
Set-Location "$LanternRoot"
New-Item -ItemType Directory -Force -Path "$logDir" | Out-Null
`$log = "$logDir\cloudflare-autostart.log"
"[`$(Get-Date -Format 'u')] Cloudflare tunnel autostart triggered" | Tee-Object -Append `$log

`$cloudflared = Get-Command cloudflared -ErrorAction SilentlyContinue
if (-not `$cloudflared) {
    "[`$(Get-Date -Format 'u')] ERROR: cloudflared not found - install with: winget install Cloudflare.cloudflared" | Tee-Object -Append `$log
    exit 1
}

# Credentials must exist - created by 'cloudflared tunnel login' (one-time)
`$credFile = "$cfCredDir\lantern-os.json"
if (-not (Test-Path `$credFile)) {
    "[`$(Get-Date -Format 'u')] ERROR: No tunnel credentials at `$credFile - run: cloudflared tunnel login" | Tee-Object -Append `$log
    exit 1
}

# Watchdog loop - cloudflared exits on network loss; restart immediately
while (`$true) {
    "[`$(Get-Date -Format 'u')] Starting cloudflared tunnel (lantern-os)" | Tee-Object -Append `$log
    & cloudflared tunnel run --config "$cfConfig" lantern-os 2>&1 | Tee-Object -Append `$log
    "[`$(Get-Date -Format 'u')] cloudflared exited (code `$LASTEXITCODE) - restarting in 5s" | Tee-Object -Append `$log
    Start-Sleep -Seconds 5
}
"@

    Write-Host ""
    Write-Host "    All three services registered:" -ForegroundColor Gray
    Write-Host "      1. $TaskName          - node server (boot + login)" -ForegroundColor Gray
    Write-Host "      2. $TaskNameDiscord   - Discord bot watchdog (+30s delay)" -ForegroundColor Gray
    Write-Host "      3. $TaskNameCloudflare - Cloudflare tunnel (+20s delay)" -ForegroundColor Gray
    Write-Host "    Auto-restarts: unlimited (1min Task Scheduler backoff + inline watchdog)" -ForegroundColor Gray
    Write-Host "    Logs: $logDir" -ForegroundColor Gray
    Write-Host "    To remove: .\scripts\Start-Lantern.ps1 -UnregisterAutostart" -ForegroundColor Gray
    Write-Host ""
    Write-Host "    Prerequisites for Discord: DISCORD_BOT_TOKEN in .env or .env.local" -ForegroundColor Yellow
    Write-Host "    Prerequisites for Cloudflare: run 'cloudflared tunnel login' once as Admin" -ForegroundColor Yellow
    exit 0
}

# ── Pre-flight ─────────────────────────────────────────────────────────────

Write-Host ""
Write-Host "  Lantern OS - Dream Journal" -ForegroundColor Yellow
Write-Host "  ──────────────────────────" -ForegroundColor DarkGray
Write-Host ""

# Check Node.js
try {
    $nodeVer = node --version 2>&1
    Write-OK "Node.js $nodeVer"
} catch {
    Write-Err "Node.js not found. Install from https://nodejs.org"
    exit 1
}

# Check repo
$serverPath = Join-Path $LanternRoot "apps\lantern-garage\server.js"
if (-not (Test-Path $serverPath)) {
    Write-Err "server.js not found at $serverPath"
    Write-Warn "Is -LanternRoot correct? Current: $LanternRoot"
    exit 1
}

# Install npm deps if missing
$nodeModules = Join-Path $LanternRoot "apps\lantern-garage\node_modules"
if (-not (Test-Path $nodeModules)) {
    Write-Step "Installing npm dependencies..."
    Push-Location (Join-Path $LanternRoot "apps\lantern-garage")
    npm install --silent
    Pop-Location
    Write-OK "Dependencies installed."
}

# ── Kill existing instances ────────────────────────────────────────────────

$existing = Get-Process -Name "node" -ErrorAction SilentlyContinue |
    Where-Object { $_.CommandLine -like "*lantern-garage*" }
if ($existing) {
    Write-Step "Stopping existing Lantern Garage instance..."
    $existing | Stop-Process -Force
    Start-Sleep -Milliseconds 500
    Write-OK "Stopped."
}

# ── Start Lantern Garage ───────────────────────────────────────────────────

Write-Step "Starting Lantern Garage on port 4177..."

$garageDir = Join-Path $LanternRoot "apps\lantern-garage"
$logPath   = Join-Path $LanternRoot "logs\lantern-garage.log"
New-Item -ItemType Directory -Path (Split-Path $logPath) -Force | Out-Null

$proc = Start-Process `
    -FilePath "node" `
    -ArgumentList "server.js" `
    -WorkingDirectory $garageDir `
    -RedirectStandardOutput $logPath `
    -RedirectStandardError "$logPath.err" `
    -PassThru `
    -WindowStyle Hidden

Start-Sleep -Seconds 2

# Health check
try {
    $health = Invoke-RestMethod -Uri "http://127.0.0.1:4177/" -TimeoutSec 5 -ErrorAction Stop
    Write-OK "Lantern Garage running (PID $($proc.Id))"
    Write-Host "    http://127.0.0.1:4177" -ForegroundColor White
} catch {
    Write-Warn "Server started but health check failed. Check: $logPath"
}

# ── Start MCP (optional) ───────────────────────────────────────────────────

if ($MCP) {
    Write-Host ""
    Write-Step "Starting MCP server on port 8771..."

    $venvPython = Join-Path $LanternRoot ".venv\Scripts\python.exe"
    $mcpScript  = Join-Path $LanternRoot "src\mcp_server\server.py"

    if (-not (Test-Path $venvPython)) {
        Write-Warn ".venv not found at $LanternRoot\.venv - MCP skipped."
        Write-Warn "Create it: python -m venv .venv && .venv\Scripts\pip install -e ."
    } elseif (-not (Test-Path $mcpScript)) {
        Write-Warn "MCP server script not found at $mcpScript - skipped."
    } else {
        $mcpLog = Join-Path $LanternRoot "logs\mcp-server.log"
        Start-Process `
            -FilePath $venvPython `
            -ArgumentList $mcpScript `
            -WorkingDirectory $LanternRoot `
            -RedirectStandardOutput $mcpLog `
            -RedirectStandardError "$mcpLog.err" `
            -WindowStyle Hidden | Out-Null

        Start-Sleep -Seconds 2
        try {
            $mcpHealth = Invoke-RestMethod -Uri "http://127.0.0.1:8771/health" -TimeoutSec 5 -ErrorAction Stop
            Write-OK "MCP server running - $($mcpHealth.slots_online) slots online"
            Write-Host "    http://127.0.0.1:8771" -ForegroundColor White
        } catch {
            Write-Warn "MCP started but health check failed. Check: $mcpLog"
        }
    }
}

# ── Summary ────────────────────────────────────────────────────────────────

Write-Host ""
Write-Host "  ──────────────────────────" -ForegroundColor DarkGray
Write-OK "Lantern is running."
Write-Host ""
Write-Host "  Open in browser: http://127.0.0.1:4177" -ForegroundColor White
Write-Host "  One-time autostart setup: .\scripts\Start-Lantern.ps1 -RegisterAutostart" -ForegroundColor Gray
Write-Host "  Logs: $logPath" -ForegroundColor Gray
Write-Host ""
