param(
    [string]$Root        = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path,
    [string]$ReportsDir  = "reports",
    [string]$PdfOutDir   = "reports/PDF",
    [string]$AppsDir     = "applications",
    [string]$RagFlatFile = "skills/lantern-rag-dollhouse/references/LANTERN-OS-RAG-DOLLHOUSE.flat.md",
    [switch]$SkipStyle,
    [switch]$SkipPdf,
    [switch]$SkipRag,
    [switch]$DryRun
)

$ErrorActionPreference = "Stop"

$reportsFullDir = Join-Path $Root $ReportsDir
$pdfFullDir     = Join-Path $Root $PdfOutDir
$appsFullDir    = Join-Path $Root $AppsDir
$ragFlatFull    = Join-Path $Root $RagFlatFile
$styleScript    = Join-Path $Root "scripts/Invoke-StyleConvergence.ps1"
$pdfScript      = Join-Path $Root "scripts/Build-SimpleReportPdf.ps1"

$stamp = Get-Date -Format "yyyyMMdd-HHmmss"
$receiptFile = Join-Path $Root "manifests/evidence/sync-rag-pdf-$stamp.json"

Write-Host "=== Sync-RagAndPdf ===" -ForegroundColor Cyan
Write-Host "Root       : $Root"
Write-Host "Reports    : $reportsFullDir"
Write-Host "PDF output : $pdfFullDir"
Write-Host "RAG flat   : $ragFlatFull"
if ($DryRun) { Write-Host "[DRY RUN]" -ForegroundColor Yellow }

# Collect all .md sources: reports + applications
$mdSources = @(
    Get-ChildItem -Path $reportsFullDir -Filter "*.md" -File -ErrorAction SilentlyContinue
    Get-ChildItem -Path $appsFullDir    -Filter "*.md" -File -ErrorAction SilentlyContinue
) | Where-Object { $_ -ne $null }

Write-Host "`nFound $($mdSources.Count) .md files to process"

if (-not (Test-Path $pdfFullDir)) {
    if (-not $DryRun) { New-Item -ItemType Directory -Path $pdfFullDir -Force | Out-Null }
    Write-Host "Created PDF output dir: $pdfFullDir"
}

$results = [System.Collections.Generic.List[object]]::new()
$styleErrors = 0
$pdfBuilt    = 0
$pdfFailed   = 0

foreach ($md in $mdSources) {
    $relPath  = $md.FullName.Replace($Root + "\", "").Replace("\", "/")
    $baseName = $md.BaseName
    $pdfOut   = Join-Path $pdfFullDir "$baseName.pdf"
    $pdfRel   = "reports/PDF/$baseName.pdf"

    $result = [ordered]@{
        source     = $relPath
        pdf        = $pdfRel
        stylePass  = $null
        styleWarns = 0
        pdfStatus  = $null
        error      = $null
    }

    # --- Step 1: Style convergence ---
    if (-not $SkipStyle -and (Test-Path $styleScript)) {
        try {
            $styleOut = & powershell -NoProfile -ExecutionPolicy Bypass -File $styleScript `
                -Path $md.FullName -Report 2>&1
            $warnCount = ($styleOut | Select-String '\[ WARN\]|\[ERROR\]').Count
            $errCount  = ($styleOut | Select-String '\[ERROR\]').Count
            $result.stylePass  = ($errCount -eq 0)
            $result.styleWarns = $warnCount
            if ($errCount -gt 0) { $styleErrors++ }
        } catch {
            $result.stylePass = $false
            $result.error = $_.Exception.Message
        }
    } else {
        $result.stylePass = $null
    }

    # --- Step 2: PDF build ---
    if (-not $SkipPdf) {
        # Derive a clean title from filename
        $title = $baseName -replace '-', ' ' -replace '_', ' '
        $title = (Get-Culture).TextInfo.ToTitleCase($title.ToLower())

        if ($DryRun) {
            $result.pdfStatus = "dry-run"
        } else {
            try {
                $null = & powershell -NoProfile -ExecutionPolicy Bypass -File $pdfScript `
                    -Root $Root -Source $relPath -Output $pdfRel -Title $title 2>&1
                if ($LASTEXITCODE -eq 0 -and (Test-Path $pdfOut)) {
                    $result.pdfStatus = "built"
                    $pdfBuilt++
                } else {
                    $result.pdfStatus = "failed"
                    $pdfFailed++
                }
            } catch {
                $result.pdfStatus  = "error"
                $result.error      = $_.Exception.Message
                $pdfFailed++
            }
        }
    }

    $results.Add([pscustomobject]$result)

    $statusColor = if ($result.pdfStatus -eq 'built') { 'Green' } `
                   elseif ($result.pdfStatus -eq 'failed' -or $result.pdfStatus -eq 'error') { 'Red' } `
                   else { 'Gray' }
    $styleTag = if ($result.stylePass -eq $true) { "ok" } `
                elseif ($result.stylePass -eq $false) { "STYLE-ERR" } `
                else { "skipped" }
    Write-Host ("  [{0,-8}] style:{1,-9} {2}" -f $result.pdfStatus, $styleTag, $baseName) -ForegroundColor $statusColor
}

# --- Step 3: RAG flat file sync ---
if (-not $SkipRag) {
    Write-Host "`nUpdating RAG flat file..." -ForegroundColor Cyan
    $ragDir = Split-Path $ragFlatFull -Parent
    if (-not (Test-Path $ragDir)) {
        if (-not $DryRun) { New-Item -ItemType Directory -Path $ragDir -Force | Out-Null }
    }

    if (-not $DryRun) {
        $ragLines = [System.Collections.Generic.List[string]]::new()
        $ragLines.Add("# Lantern OS RAG Flat File")
        $ragLines.Add("# Auto-generated by Sync-RagAndPdf.ps1 - $stamp")
        $ragLines.Add("# Source: $($mdSources.Count) .md files from reports/ and applications/")
        $ragLines.Add("")

        foreach ($md in $mdSources) {
            $relPath = $md.FullName.Replace($Root + "\", "").Replace("\", "/")
            $ragLines.Add("---")
            $ragLines.Add("## SOURCE: $relPath")
            $ragLines.Add("## MODIFIED: $($md.LastWriteTime.ToString('yyyy-MM-dd'))")
            $ragLines.Add("")
            $mdContent = Get-Content -LiteralPath $md.FullName -Raw -Encoding UTF8
            # Strip raw paths and command spam (first 3 lines only if they are paths)
            $mdLines = $mdContent -split "`n"
            $ragLines.AddRange([string[]]$mdLines)
            $ragLines.Add("")
        }

        $ragLines | Set-Content -LiteralPath $ragFlatFull -Encoding UTF8
        $ragSizeKb = [Math]::Round((Get-Item $ragFlatFull).Length / 1KB, 1)
        Write-Host "RAG flat written: $ragFlatFull ($ragSizeKb KB)" -ForegroundColor Green
    } else {
        Write-Host "[DRY RUN] Would write RAG flat to $ragFlatFull" -ForegroundColor Yellow
    }
}

# --- Receipt ---
$receipt = [ordered]@{
    generatedAt   = (Get-Date).ToString("o")
    evidenceClass = "sync_rag_pdf"
    stamp         = $stamp
    mdCount       = $mdSources.Count
    pdfBuilt      = $pdfBuilt
    pdfFailed     = $pdfFailed
    styleErrors   = $styleErrors
    ragUpdated    = (-not $SkipRag -and -not $DryRun)
    dryRun        = $DryRun.IsPresent
    results       = @($results)
}

$receiptDir = Split-Path $receiptFile -Parent
if (-not (Test-Path $receiptDir)) { New-Item -ItemType Directory -Path $receiptDir -Force | Out-Null }
if (-not $DryRun) {
    $receipt | ConvertTo-Json -Depth 6 | Set-Content -LiteralPath $receiptFile -Encoding UTF8
}

Write-Host "`n=== Summary ===" -ForegroundColor Cyan
Write-Host "PDFs built  : $pdfBuilt" -ForegroundColor Green
Write-Host "PDFs failed : $pdfFailed" -ForegroundColor $(if ($pdfFailed -gt 0) { 'Red' } else { 'Green' })
Write-Host "Style errors: $styleErrors" -ForegroundColor $(if ($styleErrors -gt 0) { 'Yellow' } else { 'Green' })
if (-not $DryRun) { Write-Host "Receipt     : $receiptFile" -ForegroundColor Gray }

exit $(if ($pdfFailed -gt 0) { 1 } else { 0 })
